<?php

namespace Minsal\ModeloBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProveedorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProveedorRepository extends EntityRepository
{
}
