<?php

namespace Minsal\ModeloBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ResumenIncrementoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResumenIncrementoRepository extends EntityRepository
{
	public function obtenerJson($idCompra)
	{
		$qb = $this->createQueryBuilder('r')
            ->select('r.contratos')
            ->where('r.id = :id')->setParameter('id', $idCompra);

        return $qb->getQuery()->getResult();
	}
}
